<?php

namespace App\Repository;

/**
 * PublicProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicProductRepository extends \Doctrine\ORM\EntityRepository
{
}
